### ISSUE TITLE
Create a GitHub action that does some of the repetitive work of test workflow

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-addon-template#28]
The test workflows for this template are repeated in every copied repo, so everything has to be updated when anything breaks, like 
* https://github.com/ddev/ddev-addon-template/pull/27

But I would think we could create a GitHub action that would package up most of the setup that we do, and then the action could be updated instead of having every add-on repo needing to be updated. 

I would think that at least this could be done by an action:

https://github.com/ddev/ddev-addon-template/blob/eba2da81ee29c2c8dfbfb84f9513a9354ec1405e/.github/workflows/tests.yml#L47-L54

and probably this too:

https://github.com/ddev/ddev-addon-template/blob/eba2da81ee29c2c8dfbfb84f9513a9354ec1405e/.github/workflows/tests.yml#L75-L76

Any interest @tyler36 or anybody else? Could be fun!

**Comment by julienloizelet** [comment]
Hi, I'm interested and I guess I could start working on it next week.

I think the `ddev_version` value that we pass in the `matrix` could be an input of the wanted action. 

This way, every add-on should look like : 

```
jobs:
  tests:
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false
      
    steps: 
    - uses: ddev/add-on-test-init@vx.y.z
        with:
          ddev_version: ${{ matrix.ddev_version }}

    - name: tests
      run: bats tests

```

What do you think ?
