### ISSUE TITLE
expect: bad interpreter

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev-addon-template#43]
Recently, I decided to update ddev-browsersync to use this addon template.

Unfortunately, the tests are [failing](https://github.com/ddev/ddev-browsersync/actions/runs/7719380164/job/21042508116#step:12:552).

```shell
 /home/runner/work/ddev-browsersync/ddev-browsersync/tests/test.bats: ./run-ddev-browsersync: /usr/bin/expect: bad interpreter: No such file or directory
```

The tests run fine locally, but not on github. Is this a problem in the ddev-addon-template?

DDEV-browsersync PR: https://github.com/ddev/ddev-browsersync/pull/48

**Comment by rfay** [comment]
You need to have expect installed. Is that missing from the instructions?

**Comment by tyler36** [comment]
Yes, I could not see anything in the docs.

I ended up resolving it by updating the `test.yml`

```yml
    steps:
    - name: Environment setup
      run: |
        sudo apt-get update >/dev/null && sudo apt-get install -y expect >/dev/null
```
